apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-mule-app
  labels:
    app: hello-mule-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-mule-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: hello-mule-app
    spec:
      containers:
        - name: hello-mule-app
          # This is overwritten by the CI/CD pipeline (kubectl set image) on every deploy.
          image: ghcr.io/anupriyasingh145-prog/pythonone-mule-demo:latest
          ports:
            - containerPort: 8081
          env:
            - name: http.port
              value: "8081"
          readinessProbe:
  httpGet:
    path: /      # Or your specific listener path
    port: 8081
  initialDelaySeconds: 60   # Give Mule 60 seconds to boot before checking
  periodSeconds: 10
livenessProbe:
  httpGet:
    path: /
    port: 8081
  initialDelaySeconds: 90   # Give it plenty of time before killing it
  periodSeconds: 15